version: '2'

volumes:
  node_modules:

services:
  webpack:
    build:
      context: .
      dockerfile: ./compose/webpack/Dockerfile
    volumes:
      - ./client:/app/client
      - node_modules:/app/client/node_modules
      - .webpack:/app/.webpack
    ports:
      - "8080:8080"

  django:
    build:
      context: .
      dockerfile: ./compose/server/Dockerfile
    depends_on:
      - webpack
    volumes:
      - .:/app
      - .webpack:/app/.webpack
    ports:
      - "8000:8000"
    command: /start.sh
