# Generated by Django 2.0.2 on 2018-02-09 14:26

import app.api.models
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
            bases=(app.api.models.SerializableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RiskModelField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.PositiveIntegerField()),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'])),
                ('is_required', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('FieldType.TEXT', 'TEXT'), ('FieldType.NUMBER', 'NUMBER'), ('FieldType.DATE', 'DATE'), ('FieldType.ENUM', 'ENUM')], max_length=64)),
                ('choices', models.TextField(blank=True, null=True)),
                ('risk_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='risk.RiskModel')),
            ],
            bases=(app.api.models.SerializableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RiskModelObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('risk_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_objects', to='risk.RiskModel')),
            ],
            options={
                'ordering': ('-created',),
            },
            bases=(app.api.models.SerializableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RiskModelObjectValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(editable=False, max_length=64)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.IntegerField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_enum', models.CharField(blank=True, max_length=128, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.RiskModelField')),
                ('risk_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_values', to='risk.RiskModelObject')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='riskmodelfield',
            unique_together={('risk_model', 'slug')},
        ),
    ]
