# Generated by Django 2.0.2 on 2018-02-06 13:52

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RiskModelField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.PositiveIntegerField()),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], unique=True)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=64)),
                ('is_required', models.BooleanField(default=False)),
                ('risk_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='risk.RiskModel')),
            ],
        ),
        migrations.CreateModel(
            name='RiskModelObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('risk_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_objects', to='risk.RiskModel')),
            ],
        ),
        migrations.CreateModel(
            name='RiskModelObjectValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(editable=False, max_length=64)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.IntegerField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.RiskModelField')),
                ('risk_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_values', to='risk.RiskModelObject')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='riskmodelfield',
            unique_together={('risk_model', 'slug')},
        ),
    ]
