# Generated by Django 2.0.2 on 2018-02-06 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskmodel',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='riskmodelobject',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='riskmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskmodelobject',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
