# Generated by Django 2.0.2 on 2018-02-06 15:45

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_auto_20180206_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmodelfield',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
    ]
