# Generated by Django 2.0.2 on 2018-02-08 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_auto_20180206_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskModelEnumField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='riskmodelobjectvalue',
            name='value_datetime',
        ),
        migrations.AddField(
            model_name='riskmodelobjectvalue',
            name='value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskmodelfield',
            name='type',
            field=models.CharField(choices=[('FieldType.TEXT', 'TEXT'), ('FieldType.NUMBER', 'NUMBER'), ('FieldType.DATE', 'DATE'), ('FieldType.ENUM', 'ENUM')], max_length=64),
        ),
        migrations.AlterField(
            model_name='riskmodelobjectvalue',
            name='value_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='riskmodelenumfield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.RiskModelField'),
        ),
        migrations.AlterUniqueTogether(
            name='riskmodelenumfield',
            unique_together={('field', 'value')},
        ),
    ]
