# Generated by Django 2.0.2 on 2018-02-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnyValueEnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AnyValueEnumChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anyvalue.AnyValueEnum')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='anyvalueenumchoice',
            unique_together={('field', 'value')},
        ),
    ]
